name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    name: 🚀 Lint
    timeout-minutes: 15

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v2

      - name: 📥 Install Dependencies
        run: yarn install

      - name: 💅 Build storybook
        run: yarn build

      # - name: 💅 Lint
      #   run: yarn lint
 deploy:
    name: Deploy Storybook
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build storybook docs
        run: yarn build:docs
      - name: Deploy in Vercel (prod)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: '--prod'
